pycontw/pycontw-frontend

.github/workflows/cd.yml, nuxt.config.js
1. Go to '...'
4. See error
to [how to write the perfect pull …
=> feat(cd): define workflows to deploy to gh-pages

nuxt.config.js
1. Go to '...'
4. See error
to [how to write the perfect pull …
=> fix(nuxt): correct router base for github page access

components/core/header/Header.vue, components/core/header/nav-bar/NavBar.i18n.js, components/core/header/nav-bar/NavBar.vue, components/core/links/ExtLink.vue, components/core/links/LocaleLink.vue, pages/about/code-of-conduct.i18n.js, pages/about/code-of-conduct.vue, pages/speaking/cfp.i18n.js, pages/speaking/cfp.vue, pages/speaking/recording.i18n.js, pages/speaking/recording.vue, pages/speaking/talk.i18n.js, pages/speaking/talk.vue, pages/speaking/tutorial.i18n.js, pages/speaking/tutorial.vue
- Add CFP related content
- The `*.i18n.js` in #8 have complex structures and have been simplified in this PR.
- page content is provided by program team
- [en-us version](https://hackmd.io/@pycontw/H1cdtGaqw)
- [zh-hant version](https://hackmd.io/@pycontw/B1pbilG9D)
=> Add CFP related page content

i18n/about/index.i18n.js, pages/about/index.vue, pages/index.vue
- remove unsupported sponsor list data
- add about page context with i18n
1. Go to '...'
4. See error
=> feat: remove sponsor list and add about contents

i18n/speaking/cfp.i18n.js
fix typo based on the request from the program team
=> fix(cfp): fix typo based on the request from program team

i18n/sponsor/prospectus.i18n.js
Update the tentative dates for sponsors' reference.
Review the prospectus page and check its content.
=> feat(sponsor): prospectus i18n wording and content update

components/core/i18n/PageWrapper.vue, layouts/default.vue, pages/about/code-of-conduct.vue, pages/about/index.vue, pages/speaking/cfp.vue, pages/speaking/recording.vue, pages/speaking/talk.vue, pages/speaking/tutorial.vue, pages/sponsor/index.vue, pages/sponsor/prospectus.vue
Allow pages to respond to different resolutions
1. Go to '...'
4. See error
=> feat: apply rwd mechanism to pages

i18n/about/index.i18n.js, i18n/sponsor/prospectus.i18n.js, pages/about/index.vue
Modify content based on the request from the program team.
The content of about page can be found here:
- zh-hant: https://hackmd.io/_YY7Jg7CSZikBDIA8WRPwg
- en-us: https://hackmd.io/2dJXRXG9ScCRULPliWajrg
=> fix(about): modify content based on the request from program team

components/core/announce-bar/AnnounceBar.i18n.js, components/core/announce-bar/AnnounceBar.vue, components/core/announce-bar/index.js, i18n/index.i18n.js, layouts/default.vue, pages/index.vue
Add AnnounceBar and change welcome wording.
1. Go to '...'
4. See error
=> Add AnnounceBar and change welcome wording.

Dockerfile, components/core/header/Header.vue, components/core/header/HomeIcon.vue, nuxt.config.js, pages/speaking/cfp.vue, pages/speaking/talk.vue
We'd liked to change the endpoints of frontend & backend:
- frontend: `tw.pycon.org/` -> `tw.pycon.org/2021`
- backend: `tw.pycon.org/2021` -> `tw.pycon.org/prs`
Related PRs:
- [pycon.tw#997](https://github.com/pycontw/pycon.tw/pull/997)
- [pycontw-nginx#5](https://github.com/pycontw/pycontw-nginx/pull/5)
=> hotfix(route): change base route & backend endpoint

components/core/footer/FooterIcon.vue, i18n/index.i18n.js, layouts/default.vue, pages/index.vue
- Change the font size from 18 to 20 (align with design).
- Remove the button for recruiting form on the index page.
- Reduce the size & margin of the social media icon set in the footer.
The original style:
Updated style:
=> Update mobile view styling 

i18n/about/staff.i18n.js, pages/about/staff.vue
=> chore(staff): update staff list (20210418)

i18n/sponsor/prospectus.i18n.js, pages/sponsor/prospectus.vue
Update Young talent name to Young Pyckathon.
=> feat(prospectus.i18n.js): update young talent name

components/landing-focus/LandingFocusInfo.vue
=> feat(LandingFocusInfo.vue): update conference date

i18n/sponsor/prospectus.i18n.js
Add tech talk total limit and deadline.
=> feat(prospectus.i18n.js): add tech talk total limit and deadline

i18n/sponsor/prospectus.i18n.js, pages/sponsor/prospectus.vue
1. Go to '...'
4. See error
to [how to write the perfect pull …
=> feat(prospectus.i18n.js): add COVID-19 related sponsorship packages

nuxt.config.js, package-lock.json, package.json
Add Google Analytics tracking.
=> Add Google Analytics tracking

components/core/header/nav-bar/NavBar.i18n.js, components/core/header/nav-bar/NavBar.vue, components/core/header/nav-bar/NavBarHamburger.vue, i18n/about/community.i18n.js, i18n/about/history.i18n.js, pages/about/community.vue, pages/about/history.vue, pages/index.vue
- take down volunteer form
- style fix & add dropdown on navbar (mobile view) for about pages
- add links of each community on about/community page
- hide event items temporarily
=> Followup changes on about pages & navbar

components/core/announce-bar/index.js, components/core/footer/index.js, components/core/header/Header.vue, components/core/header/index.js, components/core/header/locale-switch/LocaleSwitch.vue, components/core/header/locale-switch/index.js, components/core/header/nav-bar/NavBarItemDropdown.vue, components/core/header/nav-bar/index.js, components/core/i18n/PageWrapper.vue, components/core/menu/index.js, layouts/default.vue, package-lock.json, package.json, pages/about/history.vue, tailwind.config.js
Upgrade `nuxt` (>=2.15.3) & `@nuxtjs/tailwindcss` (>=4.1.0) and add `postcss` for features (mainly JIT & more packed classes) in tailwindcss 3.0.
=> chore(deps): upgrade nuxt & tailwindcss

components/bulletins/BulletinCard.i18n.js, components/bulletins/BulletinCard.vue, components/bulletins/BulletinCardCollection.vue, components/bulletins/index.js, components/core/buttons/TextButton.vue, i18n/index.i18n.js, pages/index.vue
Figma Design:
1. Go to 'index page'
2. Click on all bulletin components
=> Add latest bulletin on index page

components/core/header/Header.vue, components/core/header/nav-bar/NavBar.vue, components/core/header/nav-bar/NavBarItemDropdown.vue, components/core/menu/Menu.vue, components/core/menu/MenuItem.vue
fix navbar dropdown based on design spec, checkout #68.
=> style: fix navbar dropdown based on design spec

components/bulletins/BulletinCard.i18n.js, components/bulletins/BulletinCard.vue, components/bulletins/BulletinCardCollection.vue, components/core/embed/Youtube.vue, i18n/registration/financial-aid.i18n.js, i18n/speaking/recording.i18n.js
Update FA-related content since the finance team has changed the FA policy.
1. TailwindCSS 2.X has a bug that makes `tailwindcss-aspect-ratio` cannot be applied in `@apply` directive (see [issue](https://github.com/tailwindlabs/tailwindcss/issues/3360)).
2. Fix FA link on the event card.
=> chore: update FA policy

components/bulletins/BulletinCard.i18n.js
=> fix: FA link in index page

i18n/about/history.i18n.js
Correct event name of PyCon TW 2021 history.
=> chore: Correct event name of PyCon TW 2021 history

components/sponsors/SponsorCard.vue, components/sponsors/SponsorCardCollection.vue, pages/index.vue
Fixed #74, but changed to 2 cards in a row instead of 3.
=> style: update sponsor list based on design spec

.gitignore, components/sponsors/SponsorModal.vue
Alter the style of sponsor light box to follow design
1. Run dev server and json server
2. Go to index
3. Scroll down to Sponsors section
4. Click any sponsor to activate the sponsor light box
5. Check styles
#71 
=> Fix issue#71

components/sponsors/SponsorModal.vue, layouts/default.vue, pages/index.vue
- Disable body scrolling when displaying sponsor modal
1. Go to 'Home Page'
2. Click on SponsorIcon'
* The scrolling on background will be disabled
#106
=> fix(SponsorModal): Disable body scrolling when displaying sponsor modal

components/sponsors/SponsorModal.vue, db.json
Show sponsors name by locale.
1. Go to index page
2. Scroll down to `sponsor-section`
3. Click on `sponsor-card`
4. check style for locales
[PR #1031 of pycon.tw](https://github.com/pycontw/pycon.tw/pull/1031) needs to be merged first
<details>
<summary> en_us </summary>
<br>
</details>
<details>
<summary> zh_hant </summary>
<br>
</details>
=> fix(SponsorModal): update sponsor name

i18n/sponsor/prospectus.i18n.js
**young inspirers sponsorship packages have typos. 
1. Go to '...'
4. See error
=> fix(i18n/sponsor/prospectus.i18n.js): fix young inspirers typo

i18n/about/history.i18n.js
- Correct event name in pycon history page.
- Update the description of 2021 year in pycon history page
=> chore(history.i18n.js): follow up event name

routes.json, store/index.js
=> fix(http): api endpoint is invalid for iOS if not ended with slash

components/core/header/HomeIcon.vue, components/error/Error.vue, components/landing-focus/LandingFocusSlogan.vue, i18n/about/privacy-policy.i18n.js, i18n/about/staff.i18n.js, i18n/covid-19/index.i18n.js, i18n/sponsor/jobs.i18n.js, layouts/default.vue, pages/about/code-of-conduct.vue, pages/about/community.vue, pages/about/history.vue, pages/about/index.vue, pages/about/privacy-policy.vue, pages/about/staff.vue, pages/conference/keynotes.vue, pages/covid19_guidelines/index.vue, pages/events/jobs.vue, pages/registration/financial-aid.vue, pages/registration/tickets.vue, pages/speaking/cfp.vue, pages/speaking/recording.vue, pages/speaking/talk.vue, pages/speaking/tutorial.vue, pages/sponsor/index.vue, pages/sponsor/prospectus.vue
- Added meta tag.
- Added missing data.
- Fixed images' alt.
#102 
#103 
- Not sure about <5. Job Posting part>, it is not in this commit so far. I guess needs to be discussed and provide more info.
=> fix(SEO): add more structured data and meta tag

i18n/about/history.i18n.js, pages/about/history.vue
chore(about/history): update page content & fix grammar based on the doc provided by the program team.
https://hackmd.io/_YY7Jg7CSZikBDIA8WRPwg
https://hackmd.io/2dJXRXG9ScCRULPliWajrg
=> chore(about/history): update page content & fix grammar

i18n/ext/live.i18n.js, pages/ext/live.vue
- Add live broadcast page
1. Go to '{host}/pycontw-2021/en-us/ext/live?token={your_token}'
- if the token is valid: 
- if the token is invalid:
=> feat(live-page): Add live broadcast page

components/jobs/JobsPanel.vue, db.json, i18n/sponsor/jobs.i18n.js
=> fix(jobs): add title in description & requirements section

pages/conference/warmups/taichungpy.vue
=> fix(warmup-event): typo

components/jobs/JobsCard.vue, components/sponsors/SponsorCard.vue, pages/events/jobs.vue, pages/index.vue
=> fix(sponsor): add alt for sponsor logo on index page

pages/index.vue
* **Bugfix**
PyCon TW do not accept sponsorship now. Remove those links to sponsor page.
=> fix(index): hide sponsor button

components/core/header/nav-bar/nav-bar-items.js, i18n/events/sprints.i18n.js, pages/events/overview.vue, pages/events/sprints.vue
Add sprint page.
preview:
<details>
<summary>zh-TW</summary>
</details>
<details>
<summary>en-US</summary>
</details>
=> feat: add events/sprints page

pages/conference/warmups/index.vue, pages/conference/warmups/pyhug.vue, pages/conference/warmups/taichungpy.vue
* **Other**
update warmup event page based on the modified information provided by program team.
=> chore: update warmup event page

components/core/header/nav-bar/nav-bar-items.js, i18n/events/open-spaces.i18n.js, pages/events/open-spaces.vue, pages/events/overview.vue
add open spaces page
preview:
<details>
<summary> zh-hant </summary>
<br>
</details>
<details>
<summary> en-us </summary>
<br>
</details>
=> feat: add events/open-spaces page

pages/conference/_eventType/_id.vue
* **Other (revert #170)**
see #172
=> revert: undo #170 (see #172 for details)

components/schedule/ScheduleEvent.vue, db.json
* **Bugfix**
Fix #174. See the change in backend server [here](https://github.com/pycontw/pycon.tw/pull/1043).
=> fix(schedule): handle i18n data

components/bulletins/BulletinCard.i18n.js
* **Other (update bulletin)**
Remove:
- Financial Aid (closed)
Add:
- HackMD collaborative note
- Open Space
=> chore: update bulletin items

i18n/index.i18n.js, pages/index.vue
Add PyCon 2022 APAC info in home page.
1. Go to home page
=> Pycon apac join us

pages/sponsor/index.vue, pages/sponsor/prospectus.vue
Fix the contact mail of sponsorship pages.
=> fix(pages/sponsor): update sponsorship email address

Dockerfile, dev.Dockerfile, docker-compose.yml
=> build(Dockerfile): Update Dockerfile for 2022

components/error/Error.vue, pages/index.vue
* **Bugfix**
Fix horizontal scroll bar appear in browser
1. Go to http://localhost:3000/
Should not see the horizontal scroll bar
=> fix(index.vue): Fix scroll bar

components/core/header/nav-bar/NavBarHamburger.vue, i18n/sponsor/index.i18n.js, pages/sponsor/index.vue
=> fix sponsorship page

components/core/header/nav-bar/NavBar.vue, components/core/header/nav-bar/NavBarHamburger.vue, pages/index.vue
* **Other (chore)**
Hide links that lead to proposal pages from index page and navbar.
=> Hide links that lead to proposal pages from index page and navbar

i18n/registration/tickets.i18n.js, pages/registration/tickets.vue
modify mandarin/english ticket info page.
Noted that this PR is blocked by https://github.com/pycontw/pycontw-frontend/pull/214.
=> Revamp ticket page

components/core/buttons/TextButton.vue, components/core/footer/FooterIcon.vue, components/core/layout/TwoColWrapper.vue, i18n/about/privacy-policy.i18n.js, i18n/registration/financial-aid.i18n.js, pages/about/privacy-policy.vue, pages/registration/financial-aid.vue, pages/speaking/tutorial.vue, pages/sponsor/index.vue
* **Bugfix**
Fix button style based on [design spec](https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=0%3A1) (The `loading` style is not included in this PR). The following is the screenshot of the button designs.
Test with the following snippet
<details>
<summary>click</summary>
```html
<div class="flex flex-row">
<div class="flex flex-wrap flex-col mt-10 ml-10">
<text-button href="link" class="pb-10" large>
Large Primary
</text-button>
<text-button class="pb-10" large> Large Primary</text-button>
</div>
<div class="flex flex-wrap flex-col mt-10 ml-10">
<text-button href="link" class="pb-10">
Medium Primary
</text-button>
<text-button class="pb-10"> Medium Primary </text-button>
</div>
<div class="flex flex-wrap flex-col …
```
=> fix(design-system): button styling

components/core/header/Header.vue, components/core/header/nav-bar/ScrollableNavBar.vue, components/core/menu/Menu.vue
blocked by #218
1. make navbar scrollable
1. set screen width between 768px and 1193px
2. click arrow
=> feat: scrollable nav

pages/index.vue
* **Bugfix**
fix(index): fix invalid imported I18nPageWrapper and the layout of sponsor-cards
=> fix(index): fix invalid imported I18nPageWrapper and the layout of sponsor-cards

components/core/header/Header.vue, components/core/header/locale-switch/LocaleSwitch.vue, components/core/menu/Menu.vue
* **Bugfix**
1. fixed z-index
2. fixed the color on hover, need to be pink in both  mobile and desktop(confirmed with UI team)
1. hover on locale switch with mobile and desktop
[
](https://github.com/pycontw/pycontw-frontend/issues/203)
=> fix: navbar locale z-index & color

i18n/registration/tickets.i18n.js
* **Bugfix**
Fix Regular Ticket typo
=> fix(tickets.i18n): fit ticketRegular typo

components/core/header/nav-bar/nav-bar-items.js, components/core/i18n/PageWrapper.vue, components/jobs/JobsCardCollection.vue, components/jobs/JobsPanel.vue, i18n/sponsor/jobs.i18n.js, pages/events/jobs.vue, pages/events/overview.vue
Revise style
1. adjust text size, color for KobsPanel component
2.apply secondary color to button in  JobsPanel component
=> fix: revise style for jobs page

i18n/conference/young-inspirers.i18n.js
Add the content of speech 4
Go to page `http://localhost:3000/2022/en-us/conference/young-inspirers`
Content added for speech 4
=> feat(young-inspirers): update speech4 content

i18n/events/overview.i18n.js, i18n/registration/tickets.i18n.js, pages/registration/tickets.vue
=> feat(tickets): add sponsorship pass content

pages/index.vue
=> feat: add anchor to sponsor section

pages/conference/young-inspirers.vue
* style(young-inspirers): update to follow BEM naming
1. go to page `conference/young-inspirers`
=> style(young-inspirers): update to follow BEM naming

pages/registration/tickets.vue
* **Bugfix**
fix ticket type to ended
=> fix(ticktes): fix ticket type to ended

pages/about/community.vue
* **Bugfix**
1. open /about/community
2. adjust the screen size
https://github.com/pycontw/pycontw-frontend/issues/280
=> fix(community): font, line-height, space, transition

pages/about/staff.vue
* **Bugfix**
Correct name list.
- Go to page staff and have a check.
=> fix(staff): update staff name list

README.md, docker-compose-dev.yml, nuxt.config.js
* **Bugfix**
add config on nuxt.config.js
can see vue dev tool on console
#322
=> fix: add devtool on nuxt config

i18n/events/open-spaces.i18n.js, pages/events/open-spaces.vue, pages/events/sprints.vue
apply component “two-col-wrapper” on open space page and sprint page.
open space: #295
sprint: #282
=> feat: apply two-col-wrapper

components/schedule/ScheduleTable.vue
* **Bugfix**
Fix schedule events's wrong position
run dev and visit /conference/schedule
=> fix(schedule): correct events block position

i18n/ext/discord.i18n.js, pages/ext/discord.vue
=> feat(ext/discord): add 2022 discord guideline

i18n/ext/discord.i18n.js, pages/ext/discord.vue
**New feature**
Update the discord guideline based on 
- https://hackmd.io/@pycontw/r1IjDgrg5
- https://hackmd.io/@pycontw/S1E8GVmZ5
1. Go to https://tw.pycon.org/2022/zh-hant/ext/discord
The content of discord guideline has been updated.
N/A
No.
=> feat(ext/discord): update 2022 discord guideline

pages/registration/tickets.vue
=> feat(pages/registration): disable latebird tickets

i18n/registration/tickets.i18n.js, pages/registration/tickets.vue
* **Bugfix**
modify layout to fit the design spec
#267
=> feat: modify banner and layout for Ticket page

i18n/about/apac-community.i18n.js
Update contents to the latest version on hackmd.
Check contents specifically in:
PyCon JP
PyCon HK
PyCon PH
PyCon MY
Kiwi PyCon
Link: https://hackmd.io/JqrqYGmrTA2EB3K1m8O0MA?view#PyCon-APAC-%E7%B1%8C%E5%82%99%E7%A4%BE%E7%BE%A4%E4%BB%8B%E7%B4%B9-Introduction-to-PyCon-APAC-Organizers-Community
=> feat(community-detail): update apac community content

i18n/events/open-spaces.i18n.js
* **Bugfix**
- update 2022 open speace descrption
- [Go to page open-spaces](http://localhost:3000/2022/en-us/events/open-spaces)
=> fix(events/open-spaces): update 2022 open space descrption

.github/workflows/cd.yml
fix the repo name on `cd.yml`
change the repo name to pycontw-frontend
fix #347
=> fix: correct the repo name on cd

i18n/about/privacy-policy.i18n.js, pages/about/privacy-policy.vue
Update to 2023 content
1. npm run dev
2. go to page `/2023/en-us/about/privacy-policy` or `/2023/zh-tw/about/privacy-policy`
https://deploy-preview-355--ephemeral-sable-89c7e0.netlify.app/zh-hant/about/privacy-policy
closes #354
=> feat(privacy-policy): update to 2023 content

README.md
add instructions for archiving the historical websites
=> docs(readme): add instructions for archiving the historical websites

i18n/speaking/recording.i18n.js, pages/speaking/recording.vue
update i18n, font-size, padding, structure
1. go to /speaking/recording
2. test languages (zh-hant, en-us)
3. test screen width (@min-width: 768px, 1024px)
#341
=> feat(recording): upd to 2023

i18n/speaking/tutorial.i18n.js, pages/speaking/tutorial.vue
update i18n, font-size, padding, structure
1. go to /speaking/tutorial
2. test languages (zh-hant, en-us)
3. test screen width (@min-width: 768px, 1024px, 1440px)
#340
=> feat(how-to-propose-a-tutorial): upd to 2023 

i18n/about/code-of-conduct.i18n.js
=> [#364] feat: update CoC info for 2023

components/core/layout/TwoColWrapper.vue, components/core/steps/Steps.vue, i18n/speaking/cfp.i18n.js, pages/speaking/cfp.vue
2023 CFP 頁面
- Path: `/speaking/cfp`
- Check both zh-hant and English.
Figma: https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=5180%3A25237&t=YBzPw3MQMXsnT7N0-0
https://user-images.githubusercontent.com/11289171/211958499-5d4043b6-fa30-4372-979e-40c5f00becc7.mov
https://user-images.githubusercontent.com/11289171/211958493-73e99751-97ae-46ca-b637-571b911681dc.mov
#336 
NA
=> [#336] feat: 2023 cfp page

i18n/speaking/talk.i18n.js, pages/speaking/talk.vue
1.  Apply two-col-wrapper
2. Update 2023 content to the page.
1. Go to speaking/talk
2. Check the content in English and Chinese
3. Check the style and see if fit the design on Figma
See Figma: https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=39%3A1327&t=bgd3UTBIgUXcPXbT-0
#337
=> [337] feat(speaking/talk): modify for 2023 design

i18n/speaking/cfp.i18n.js
在 CFP 的「如何提交您的稿件」地方加上
```
因應 COVID-19 疫情逐漸穩定，今年演講與專業課程將會以實體會議形式舉辦，建議講者來到現場與會眾互動。若有不可抗力之因素，您仍可以依照自身狀況選擇是否親自前來。
Since COVID-19 become stable, we recommend attending the meeting venue in person. If you have personal reasons, you may ask to give your talk or tutorial remotely.
```
- Ref: https://docs.google.com/document/d/1svthuR5jZM8-rw7M2yZqn5LkjR_1NbhBjmGZqjsDsdE/
1. Path: `/2023/zh-hant/speaking/cfp` & `2023/en-us/speaking/cfp`
2. Check the description of "提交稿件 / How to Submit Your Proposal" both zh-hant and English.
#336 
NA
=> [336] feat: update description of submitting proposal

components/core/buttons/TextButton.vue, config/pageLanding.js, pages/index.vue
- `TextButton` 新增一個 `bordered` 的樣式用於首頁
- Path: `/2023/zh-hant` / `2023/en-us`
- Check both zh-hant and English.
#374 
- Figma: https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=5132%3A45173&t=XPvd34Vtdlkzx6rO-0
=> [374] feat: add bordered style for TextButton

.github/workflows/cd.yml, nuxt.config.js, package-lock.json, package.json, pages/conference/_eventType/_id.vue, pages/conference/_eventType/index.vue, pages/conference/keynotes.vue, pages/conference/schedule.vue, pages/events/jobs-gather.vue, pages/events/jobs.vue, pages/index.vue
* **Bugfix**
* **Breaking change** (any change that would cause existing functionality to not work as expected)
https://baby230211.github.io/pycontw-frontend/zh-hant
=> feat: add dynamic routes configuration for generate

i18n/registration/financial-aid.i18n.js, pages/registration/financial-aid.vue
Update content to 2023 including deadline and external link.
1. 確認日期已更新至2023
2. 確認財務補助申請表單可連結至https://lihi1.com/433eL
#383
=> feat-financial-aid: update content to 2023

i18n/registration/financial-aid.i18n.js
=> feat: update financial aid content

configs/router.js, nuxt.config.js, package-lock.json, package.json
* **Bugfix**
open in google link site:https://tw.pycon.org/2021/
choose in search result "頁庫存擋"
you open page webcache page
then page will redirect to 404
show correctly on webcache page
=> fix: webcache 404 error page on 2021

configs/router.js, nuxt.config.js, package-lock.json, package.json
* **Bugfix**
open in google link site:https://tw.pycon.org/2022/
choose in search result "頁庫存擋"
you open page webcache page
then page will redirect to 404
show correctly on webcache page
=> fix: webcache 404 error page on 2022

i18n/registration/financial-aid.i18n.js
* **Content Update**
update content-auxiliary items
=> [fix]Financial-Aid-content-update

components/intro/Intro.i18n.js, components/intro/Intro.vue, configs/pageLanding.js, i18n/index.i18n.js, pages/index.vue, store/index.js
* change pyconapac intro into pycontw
* add buyTickets button to index page
1. setup dev server
2. go to index page
=> Add buyTicket btn to index and update intro section

components/intro/Intro.i18n.js
- Add descriptions of the venue on index page
1. setup dev server
2. go to index page
3. check `EN` and `ZH` modes
=> feat: update pycontw intro

nuxt.config.js, package-lock.json, package.json
resolve #414
note that i've added a sitemap index in the archive repo:
- https://github.com/pycontw/pycon_archive_past_website/tree/gh-pages/sitemaps
- https://github.com/pycontw/pycontw-nginx/pull/18
=> feat: add sitemap module

nuxt.config.js, package-lock.json, package.json
related issue: #414 
related PR: #416
https://tw.pycon.org/2022/sitemap.xml
=> feat: add sitemap to 2022 website

i18n/conference/keynotes.i18n.js, i18n/conference/speeches.i18n.js, store/index.js
Update i18n description of talks/tutorials page
1. go to page `conference/talks` and `conference/tutorials`
=> feat(conference/index): update talks intro

i18n/venue/index.i18n.js
update return time of shuttle service and some punctuation
ref: https://discord.com/channels/752904426057892052/1083766112220626944/1139770620977106994
Check `/venue`
=> feat(venue): update shuttle service time

configs/pageTickets.js, i18n/registration/tickets.i18n.js
=> feat(tickets): update selling status of premium tickets

pages/registration/tickets.vue
* **Bugfix**
check ticket info page on en lang
=> fix(ticket): ui broken on ticket image

configs/pageTickets.js
=> feat: close group-buy corporate and reserved tickets

i18n/events/open-spaces.i18n.js, pages/events/open-spaces.vue
[Discord discussion thread](https://discord.com/channels/752904426057892052/1136678719319183470/1142042125807136872)
=> chore(open-spaces): update content for 2023

i18n/conference/panel-discussion.i18n.js, pages/conference/panel-discussion.vue
[discord link](https://discord.com/channels/752904426057892052/753841328198254642/1144521077037486100)
=> chore(panel-discussion): add links to slido & hackmd

i18n/ext/discord.i18n.js, pages/ext/discord.vue
update content to 2023 version
1. Type “<localhost>/2023/en-us/ext/discord” in url
2. Scroll and check if the content is correct(no 2022, APAC etc)
3. Check again in “<localhost>/2023/zh-hant/ext/discord”
#446
=> feat-update-discord-to-2023

pages/index.vue
Remove typhoon pop up 
1. go to "/2023/zh-hant" and "/2023/en" and see if pop up window disappear.
=> (landing page) Remove typhoon pop up 

pages/venue/index.vue
* **Bugfix**
Fix page import issue due to [last 2 commits](https://github.com/pycontw/pycontw-frontend/pull/459) could break generate command
1. `npm run generate`
=> fix: page import error

i18n/speaking/tutorial.i18n.js
Update the content of **How to Propose a Tutorial**
resolve #472
=> feat: update How to Propose a Tutorial

i18n/speaking/talk.i18n.js, pages/speaking/talk.vue
=> feat-update_2024_talk_content

i18n/about/code-of-conduct.i18n.js, pages/about/code-of-conduct.vue
add link for code of conduct
resolve https://github.com/pycontw/pycontw-frontend/issues/484
=> 行為準則 Code of Conduct (CoC) - 官網 add link

pages/speaking/cfp.vue
=> fix: cfp div error

i18n/speaking/cfp.i18n.js, pages/index.vue, store/index.js
show proposal system for staging
=> proposal page switch on

i18n/about/history.i18n.js, i18n/about/index.i18n.js, pages/about/history.vue, pages/about/index.vue
=> Update about page 2024

i18n/about/code-of-conduct.i18n.js
=> feat(about): fix typo in CoC zh version

i18n/about/code-of-conduct.i18n.js, i18n/about/privacy-policy.i18n.js, pages/about/code-of-conduct.vue
* **Bugfix**
1. Update CoC page with license statement
2. Update privacy policy page with license effective date
1. Run dev server
resolve #495 
<details>
<summary>Screenshot of CoC (zh-hant)</summary>
</details>
<details>
<summary>Screenshot of CoC (en-us)</summary>
</details>
<details>
<summary>Screenshot of privacy policy (zh-hant)</summary>
</details>
<details>
<summary>Screenshot of privacy policy (en-us)</summary>
</details>
=> feat: update CoC license statement

pages/about/privacy-policy.vue
* **Bugfix**
Ray suggest to change a line position in privacy policy.
1. Run Dev Server 
Related to #495
=> fix: change policy privacy position

i18n/registration/financial-aid.i18n.js, pages/registration/financial-aid.vue, store/index.js
A branch for ongoing PRs checked by PM and issue requesters before the commits merge into main branch.
=> chore: branch for PRs review on staging

pages/speaking/cfp.vue
* **Bugfix**
Fix CFP AoE URL link
=> modify cfp aoe url

pages/index.vue, store/index.js
* **Chore**
hide cfp button on index page
=> chore: hide cfp button on index page

nuxt.config.js, store/index.js
* **Bugfix**
Add some checking to prevent iteration on undefined value.
1. check if netlify build works well
=> fix: prevent generation failed due to 4xx, 5xx api error

store/index.js
贊助組好像想把這個開關打開 ([ref](https://discord.com/channels/752904426057892052/753841328198254642/1224323639743086673), 但我找不到票)
=> chore: show sponsor section on index page

pages/index.vue
* **Bugfix**
Remove unnecessary line to prevent rendering side-effect on sponsor section.
1. checkout preview deploy
=> fix(index): fix rendering bug on sponsor section

components/core/header/nav-bar/NavBar.i18n.js, components/core/header/nav-bar/nav-bar-items.js, i18n/speaking/poster-session.i18n.js, pages/speaking/cfp.vue, pages/speaking/poster-session.vue
1. modify navbar order
2. modify poster session description
3. modify AoE time link
=> feat: modify poster session description

pages/speaking/poster-session.vue
Update link of poster form to https://bit.ly/web-cfp-2024
=> feat[poster-session]-update_link

components/core/layout/Banner.vue, configs/pageTickets.js, i18n/registration/tickets.i18n.js, pages/registration/tickets.vue, store/index.js
Release 2024 Ticket Info 
1. Go to “http://localhost:3000/2024/zh-hant/registration/tickets"
2. Check if content has been updated and matched the document: https://docs.google.com/document/d/1fqyk_UEdX1k44xjHzUGevWDQ8PgsIQ9_T32DmTQ_bRw/edit.
3. Repeat step 1-2 for english version “http://localhost:3000/2024/en-us/registration/tickets”
#523
=> feat(reg/tickets): update content to 2024 in ticket page

.eslintrc.js, package-lock.json, package.json
* **Other **
解決在windows環境下，run json-server 出現的錯誤
1. 在vscode的terminal執行npm run json-server
2. 在vscode的terminal內會顯示  Home  http://localhost:9876
3. 到瀏覽器上輸入 http://localhost:9876，成功跑出畫面。
=> chore(env): adjust scripts for json-server

configs/pageLanding.js, configs/pageTickets.js, pages/index.vue, store/index.js
- Toggle ticket button on landing page
- Adjust the size of buttons
1. Go to landing page "http://localhost:3000/2024/en-us"
2. Check if "Buy Tickets Now" btn is on the page
=> feat(reg/tickets): toggle tickets btn on landing page

configs/pageTickets.js
Switch ticket buttons into selling phase.
更新售票狀態從coming soon 到 selling:
=> feat(reg/tickets): btn switch to selling

i18n/speaking/poster-session.i18n.js, pages/speaking/poster-session.vue
* **Update UI**
Go to the path /speaking/poster-session
=> feat(proposal): change poster-session submit date UI

i18n/events/overview.i18n.js, pages/events/overview.vue
Update sprint card at event overview page.
1. `npm run dev`
2. checkout path `/2024/en-us/events/overview`
<details>
<summary>Screenshots</summary>
</details>
=> feat(event/overview): edit sprint to post-event activity

store/index.js
Open job lists on 2024 sites.
1. Check if "http://localhost:3000/2024/zh-hant/events/jobs" is appeared with samples.
=> feat(events/jobs): toggle job lists

components/intro/Intro.i18n.js
Update intro in index page to 2024
Doc: https://docs.google.com/document/d/1Zmus35R5rGtY8UqcZMYeY6G8vBNm703o9lcytDk-LCA/edit#heading=h.dhqtrv9uj5ao
1. Go to path/2024/zh-hant and  path/2024/en-us 
PR #539
=> feat(intro): update to 2024 version

configs/pageTickets.js
Switch tickets to "ended" including
- premium
- individual
- concession
=> chore(tickets): switch tickets status

configs/pageTickets.js
revert PR #562 
售票期限延長
https://discord.com/channels/752904426057892052/755649462382231552/1270788417550028974
=> Revert "Merge pull request #562 from pycontw/feat/close-tickets"

components/events/SpeechCard.vue, components/schedule/ScheduleRoom.vue
* **Style**
Change the R0 room name to PSF Hall in 2024
=> style: Change the R0 room name to PSF Hall in 2024

components/core/header/nav-bar/NavBar.i18n.js, i18n/conference/poster-session.i18n.js, pages/conference/poster-session.vue
[需求參考](https://discord.com/channels/752904426057892052/1243874257528815677/1274062091162095626)
=> feat(poster-session): adjust content

i18n/events/overview.i18n.js
Update lightening talk content
1. `npm run dev`
2. Go to `http://localhost:3000/2024/en-us/events/overview`
=> feat(i18n): update lightening talk content

components/core/header/nav-bar/nav-bar-items.js, i18n/speaking/cfp.i18n.js, i18n/speaking/talk.i18n.js, pages/speaking/cfp.vue
Update the content of cfp.
#591
=> feat: update the cfp's content

pages/index.vue, store/index.js
open the proposal system, but haven't changed the 2025 proposal page.
=> proposal system

.github/workflows/ci.yml, i18n/speaking/cfp.i18n.js
因大會日期後續有變更，所以請更改 CFP 大會日期為 9/5-9/7
staging 連結 : http://staging.pycon.tw/2025/zh-hant/speaking/cfp
=> feat:  modify  CFP date begin at 9/5

configs/pageSponsors.js, i18n/sponsor/index.i18n.js, store/index.js
1. 更新贊助頁面的文案(中英文)
2. 更新贊助書的連結
3. 將 header 的贊助選項開啟
贊助頁面文案 : https://docs.google.com/document/d/1_dd9q9yRtUvSngH3jeQnONyoty26KtvhtE0ivalRgQA/edit?usp=sharing
=> Feature #601 update 2025 sponsor page

store/index.js
=> feat: open the overview

pages/index.vue
* **Bugfix**
官網圖片截到
https://discord.com/channels/752904426057892052/1375735769271894016
=> fix:css for the png

components/core/header/nav-bar/nav-bar-items.js, i18n/speaking/cfp-poster.i18n.js, pages/speaking/cfp-poster.vue
=> feat: add the cfp poster page

components/core/header/nav-bar/nav-bar-items.js
remove the navbar for the poseter-session
=> fix:remove the link

README.md
update `README.md` to include instructions for building in different environments.
=> docs: add note about .env file for API_URL_BROWSER configuration

components/reviewers/Reviewers.vue
Added cursor pointer on reviewer photo
=> fix: add cursor pointer on image

components/events/SpeechCard.vue, i18n/conference/speeches.i18n.js, i18n/events/overview.i18n.js, store/index.js
- 開啟 talks 與 tutorials 頁面
- 調整地點編號
- 調整文案
=> feat: toggle on tutorials and talks page

pages/conference/poster-session.vue
=> fix: poster-session

pages/conference/poster-session.vue
=> fix: the link of coc

i18n/conference/panel-discussion.i18n.js
* **Bugfix**
更新 Panel Discussion 的 speechTitle
=> fix: update panel discussion speechTitle

i18n/conference/poster-session.i18n.js
* **Bugfix**
更新 poster session 的成員資訊
=> fix: update poster session poster list member

i18n/conference/poster-session.i18n.js
* **Bugfix**
update poster-session posters
=> update poster-session posters

components/schedule/ScheduleGrid.vue
* **Bugfix**
- make schedule grid column flexible
=> fix: make schedule grid columns flexible instead of fixed

components/schedule/ScheduleEvent.vue, pages/conference/keynotes.vue
* **Bugfix**
#688 有嘗試修正滾動問題，#691 後又壞了。所以再修一次
=> fix: correctly scroll to keynote speaker

i18n/events/lightning-talk.i18n.js
* **Bugfix**
1. 將英文的 lightning talk 加 s
=> fix lightning talks content

pages/conference/_eventType/index.vue
* **Bugfix**
#663 導致 og:description 沒顯示正確的文案
=> fix(talks): metaInfo

i18n/venue/index.i18n.js
=> fix(parking): wrong car info data

components/events/SpeechCard.vue, components/schedule/ScheduleRoom.vue, pages/conference/_eventType/_id.vue
* **Bugfix**
- 83-yi-ps: Young / Post  to Young / Poster
#702
=> feat(conference): add new room mappings for additional venues 

configs/pageTickets.js
=> fix:open tickets
