- components/core/header/Header.vue
- components/core/header/locale-switch/LocaleSwitch.vue
- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarItemDropdown.vue
- components/core/menu/Menu.vue
- components/core/menu/MenuItem.vue
- components/core/menu/index.js
- To show the hierarchy of different pages, the navigation bar requires a dropdown component to allow users to click on the sub pages
- create `menu`, `menu-item` components
- create `nav-bar-item-dropdown` using the above-mentioned components
- apply the `nav-bar-item-dropdown` to the navigation bar items and also the language switch
- improve minor layout changes on the header for better ui/ux
1. Go to '...'
4. See error
Add any other context about the problem here. You may also want …
> feat(comp): create dropdown component

- components/core/header/nav-bar/NavBar.i18n.js
- components/core/header/nav-bar/NavBar.vue
- i18n/index.i18n.js
- pages/index.vue
Add Links to the volunteer form
1. Two buttons are added on the index page. One for the sponsor page & one for the volunteer form.
2. A new navbar item named `volunteer` is added and links to the volunteer form.
> feat(navbar): add new item for ext-link to volunteer form

- components/core/header/HomeIcon.vue
- docker-compose-dev.yml
- nuxt.config.js
- The current website fails to display the favicon after adding the router base in #23. Should add the route base in the favicon link.
- The router base `/2021` is also added to dev env for consistency with production env.
> fix(favicon): correct favicon link

- components/core/header/HomeIcon.vue
- pages/index.vue
The relative path of `static` folder is added to the url of static images since the changes in #25 don't work and still cannot get the correct URLs. (Based on the [doc](https://nuxtjs.org/docs/2.x/directory-structure/static/#static-assets), if the router base is defined, the url is automatically handled by nuxt only when the `nuxt-link` is used.)
> fix(static): correct the url of images in static folder

- layouts/default.vue
Add URL without year as canonical URL for better SEO.
e.g. the canonical URL of `https://tw.pycon.org/2021/en-us/sponsor/prospectus` is `https://tw.pycon.org/en-us/sponsor/prospectus`.
> feat(page): add url without year as canonical url

- components/core/footer/Footer.vue
The link to Facebook fan page in the footer is wrong.
> fix: correct facebook fan page link

- components/core/footer/Footer.i18n.js
- components/core/footer/Footer.vue
- components/core/footer/FooterHistory.vue
- components/core/links/ExtLink.vue
- pages/about/index.vue
1. remove history website links [pages - about - index]
2. add history website links on footer [components - core - footer]
- edit Footer.i18n.js
- edit Footer.vue
- add new file [FooterHistory.vue]
- change footer.vue template class to "h-24" for more reasonable hight temporary
- change ExtLink default color
1. Go to ' landing page '
2. switch en, zh to check footer
> Add conference website links section in footer

- components/core/header/HomeIcon.vue
- components/sponsors/SponsorCard.vue
- components/sponsors/SponsorCardCollection.i18n.js
- components/sponsors/SponsorCardCollection.vue
- components/sponsors/SponsorModal.i18n.js
- components/sponsors/SponsorModal.vue
- components/sponsors/index.js
- db.json
- i18n/index.i18n.js
- pages/index.vue
- Add mock data for sponsor list API.
- Implement sponsor list on index page & affiliated modal.
<details>
<summary>web view</summary>
</details>
<details>
<summary>mobile view (iPhone 6/7/8)</summary>
</details>
<details>
<summary>web view</summary>
</details>
<details>
<summary>mobile view (iPhone 6/7/8)</summary>
</details>
> feat(sponsor): implement sponsor list on index page

- Dockerfile
- API_URL_BROWSER only allow `https` as URL schema
- BASE_URL should be the path in docker network and schema is not needed
> fix(Dockerfile): correct BASE_URL & API_URL_BROWSER

- components/sponsors/SponsorCard.vue
For the sponsor logo with colored background, the border on the card has inconsistent width, as shown below.
Thus, the border radius is also applied to the logo image.
> feat(index): add border radius for sponsor logo

- Dockerfile
The current `API_URL_BROWSER` is `pycon.tw` and the app is failed to send the request with `@nuxt/http`. Use redirect destination `tw.pycon.org` instead fixes this issue.
> fix(Dockerfile): use tw.pycon.org as API URL

- components/landing-focus/LandingFocusSlogan.vue
The indent of the current slogan on the index page does not follow the Python syntax, which makes Pythonistas uncomfortable. 
Use 2 spaces instead.
1. Open the index page & show the slogan to someone who codes in Python. They are ought to complain about the indentation.
After the change, Python coders are expected to believe it's a great slogan.
What about the errors from the linter?
> chore: follow Python syntax for slogan

- components/core/buttons/TextButton.vue
move stylesheet's class from <button> tag to <a> tag
1. go to homepage index and click on sponsor us & be a sponsor
1. It only worked for clicking on words("sponsor us"/"be a sponsor") to go to the sponsor page before, but now it works for the whole button.
1. Not sure if this is the best way to fix this.
> Fixed the click problem of homepage's sponsor link

- components/core/embed/Youtube.vue
- components/core/i18n/PageWrapper.vue
- components/core/tabs/Tab.vue
- components/core/tabs/Tabs.vue
- components/landing-focus/LandingFocusInfo.vue
- db.json
- i18n/conference/keynotes.i18n.js
- i18n/sponsor/prospectus.i18n.js
- package-lock.json
- package.json
- pages/conference/keynotes.vue
- routes.json
- store/index.js
- tailwind.config.js
Add keynote page (`<host>/<base>/<lang>/conference/keynotes`).
https://user-images.githubusercontent.com/24987826/123493898-95917e00-d650-11eb-8949-cecc88ac1d42.mp4
> feat: implement keynote page

- components/core/tabs/Tabs.vue
- pages/conference/keynotes.vue
The style of the tab component has changed:
Current Design:
New Design:
> style: update tab colors

- pages/sponsor/prospectus.vue
Fix the sponsor package levels gird layout.
1. Run dev server and json server
2. Go to sponsor page
3. Click prospectus link
4. Check grid styles
Right style without padding left in sponsor package levels section
> style: fix prospectus page 

- components/sponsors/SponsorModal.vue
Thanks @allen91wu for discovering this issue!
> fix(sponsorModal): the height of intro is too small on mobile view

- .github/pull_request_template.md
- i18n/about/history.i18n.js
fix the typo in the following screenshot
simplify github pull request template
The second 2020 should now become 2021
> fix 2021 english title typo on history page

- components/core/footer/FooterHistory.vue
* **Bugfix**
Add color #c2a53a to word 'history' on footer.
> fix(footer): add color to word 'history'

- components/bulletins/BulletinCard.i18n.js
- components/core/footer/FooterIcon.vue
- layouts/default.vue
* **Bugfix**
* temporarily change youtube link to uuid
* our customized link is temporraily disable and will be enabled again around early Sep
click the youtube link and it should be accessible after this fix
same above
> fix: temporarily change youtube link to uuid

- components/core/tabs/Tabs.vue
- pages/conference/keynotes.vue
* **Bugfix**
- Fix keynote `font-size` and `font-weight` based on design spec.
- Go to the keynote page.
#128
> style: fix keynote font style based on design spec

- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarHamburger.vue
- components/core/header/nav-bar/nav-bar-items.js
* **Bugfix**
The newer version Vue mistakenly recognizes the constant obj in a separated javascript (`/components/core/header/nav-bar/nav-bar-items.js` in our case) as a component. The following error occurs when Vue initializes the components.
Solution: export a constant in `nav-bar-items.js` rather a module, which makes Vue not to take it as a component.
> fix(navBarItems): vue mistakenly recognize constant obj as component

- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarHamburger.vue
- components/core/header/nav-bar/nav-bar-items.js
- nuxt.config.js
We'll receive warnings when run the dev server:
The root cause is [nuxt/components](https://github.com/nuxt/components) tries to render `js` files under `components` directory as component, which mistakenly regards those `js` files for exporting components in a module (e.g. `components/jobs/index.js`) as a component.
Update `nuxt.config.js` to only render `*.vue` files to suppress the reexport warning and also allow us reverting #146.
> chore: exclude js files to be initialized as components

- mock-server.Dockerfile
* **Bugfix**
- Updated docker environment set up to make mock-server work fine.
- I'm not sure why `json-server-middlewares.js` didn't configure in Dockerfile, maybe has another reason. 😅
> chore: maintain mock-server docker environment

- components/schedule/ScheduleEvent.vue
- nuxt.config.js
- pages/conference/keynotes.vue
* **Bugfix**
Navigate and scroll to corresponding speaker on keynote page when user clicks on schedule.
https://user-images.githubusercontent.com/13831865/130480148-c28498bc-cd8d-4c2d-aa21-4f5aa1bf9f25.mov
> fix: add scrollToHash behavior when navigating from schedule to keynotes page

- components/bulletins/BulletinCard.i18n.js
- components/bulletins/BulletinCard.vue
- components/bulletins/BulletinCardCollection.vue
- components/core/buttons/TextButton.vue
- components/core/titles/H2.vue
- components/core/titles/LandingH2.vue
- components/core/titles/index.js
- pages/index.vue
* **Bugfix**
1. Changed card width to 214px in `BulletinCard.vue` 
-> Solved `1st` in the issue's Expected Behavior.
2. Added `font-bold` in `BulletinCard.vue`.
-> Solved `4th` in the issue's Expected Behavior.
3. Changed「閱讀」to「前往閱讀」in `BulletinCard.i18n.js` .
-> Solved `5th` in the issue's Expected Behavior.
---
4. For `2nd` and `3rd` which are mentioned in the issue's Expected Behavior. (Design Team wanted the border-width to always be 4px on the cards, and to always be 3px on the button.). So,
- I remained `border-4` in `BulletinCard.vue` to solve `2nd`.
- Added `bulletin props` to solve `3rd`.
-> Solved `2nd` & `3rd` in the issue's Expected Behavior.
1. On mobile view, `justify-start` caused the whole section isn't in the center position, I change it to `justify-center`. But since we …
> style: fix bulletin card based on design spec

- components/jobs/JobsCard.vue
- components/jobs/JobsCardCollection.vue
* **Bugfix**
The sponsor card on job listing page is too large, which makes the description section is too small on certain devices. See the [discord discussion](https://discord.com/channels/752904426057892052/755828862054695125/885208238583316622) for detail.
Update the card size to design spec (120x100) to ease this issue.
> chore: smaller job cards

- components/core/tabs/Tabs.vue
- pages/conference/_eventType/_id.vue
* **Bugfix**
[WHY]
The visibility of Tab component is simultaneously controlled by Tabs component & speech detail page, which causes the slido tab is always shown after component init.
[HOW]
Create a new event listener for selecting the first tab and trigger the event after component initialization in speech detail page.
> fix: slido tab displaying issue

- i18n/ext/discord.i18n.js
- pages/ext/discord.vue
- pages/ext/live.vue
* **Bugfix**
Fix wrong rendering result in `ext/live` and `ext/discord` when giving correct token
Go to '{host}/pycontw-2021/en-us/ext/live?token={your_token}' or '{host}/pycontw-2021/en-us/ext/discord?token={your_token}'
- if the token is valid: 
- if the token is invalid:
> fix(ext): Fix wrong rendering when giving correct token

- pages/conference/_eventType/_id.vue
* **Bugfix**
In the page component `pages/conference/_eventType/_id.vue`, the `og:title` and `og:description` won't act properly.
The reason why they don't work is that the fields of meta tags, `og:title` and `og:description`, weren't updated after fetching data asynchronously for the dynamic page contents.
Ensure that the async data is updated for the meta tags before the server sending rendered HTML to clients.
1. Navigate to the page of Conference -> Talks -> _[Any talk]_
2. Inspect elements and look at the `<head>` section of DOM
3. Refresh the search for `og:description` and paying attention to the `<title>` tag as well
4. See that `<title>` is the `<talk's title> | PyCon Taiwan 2021` and the `og:description` is the abstract of the talk without …
> fix(vue-meta): fix meta tags for reactivity

- components/core/links/LocaleLink.vue
- components/schedule/ScheduleBlock.vue
- pages/conference/keynotes.vue
* **Bugfix**
Follow Figma design to fix the style of schedule table on mouse hovering
https://user-images.githubusercontent.com/13831865/131272171-c46c46ce-89f0-416c-8eb4-18b30eaef479.mov
> fix: schedule hovering style

- components/jobs/JobsCardCollection.vue
- pages/events/jobs-gather.vue
- Add a job listing page for Gather Town's layout.
- The route for this page is `/events/jobs-gather`. 
(The original job listing page for the website is `/events/jobs`.)
1. Go to [http://ocalhost:3000/2021/en-us/events/jobs-gather](http://localhost:3000/2021/en-us/events/jobs-gather)
2. And you can check this page.
- It should look like the screenshots below:
<details>
<summary>zh-hant</summary>
</details>
<details>
<summary>en-us</summary>
</details>
After having a discussion with Matt, A specific CSS style(`size`, `padding`, `margin`....) in mobile view will not be considered.
> feat: add job listing page for gather town layout

- i18n/events/sprints.i18n.js
- pages/events/sprints.vue
Could resolve issue #191 
For PyCon APAC 2022, we prepare new contents for sprint event.
In this PR, we update these latest info into code
Run the server and go to
- http://localhost:3000/2021/en-us/events/sprints
to check the result
The content should be the same as
https://docs.google.com/document/d/1TkPBCrLA2Jo8kZsvye-QCwzkIlj0TQ5X7gDE411Xnc4/edit?usp=sharing (Need permission)
> feat: update sprints info for 2022

- pages/speaking/cfp.vue
Since the previous program teams' mail address, program@pycon.tw will be deprecated soon, this PR aims to replace it with a new email address(program@python.tw).
cc @jordanSu
> Update PyConTW program team's mail address

- components/core/header/nav-bar/NavBarItemDropdown.vue
add navbar-dropdown transition
1. Change the position of event trigger when mouseenter and mouseleave
2. Add two transition tags to template. One for fade in and out, the other for being mask of navbar item.
3. Add css relate to transition animation.
When navbar items were hovered, the dropdown menu will be active,
#231
> add navbar-dropdown transition

- components/core/i18n/PageWrapper.vue
- tailwind.config.js
* **Bugfix**
Adjust size and position of background image elements
1. Change `backgroundPosition`, and add `backgroundSize` properties in `tailwind.config`.
2. Add class `bg-bgsize` at `.page-wrapper` in `PageWrapper.vue.`
Adjust position of background image elements, and make them smaller.
#250
> fix(pagewrapper.vue): tune background-size and background-position

- nuxt.config.js
- package-lock.json
- package.json
- Support marketing team. Check out [discord discussion](https://discord.com/channels/752904426057892052/755831572586037691/990554820970692699).
- Add [nuxt-facebook-pixel-module](https://www.npmjs.com/package/nuxt-facebook-pixel-module) and enable it by modifying nuxt config.
> feat: add meta pixel tracker

- i18n/conference/keynotes.i18n.js
**Bugfix**
There are some overdue information on keynote page.
Hence this PR update keynote info to the latest.
The keynote page information is up-to-date
None
None
> fix(keynotes): Update keynote info for PyCon APAC 2022

- i18n/events/sprints.i18n.js
- pages/events/sprints.vue
**New feature**
Update Summer Sprint info for PyCon APAC 2022
The updated Summer Sprint info should be displayed on Sprints page
None
None
> fix(sprints): Update summer sprint info for PyCon APAC 2022

- mock-server.Dockerfile
* **Bugfix**
This is needed since the mock server is run under a different domain by the docker-compose script. Without disabling CORS, browsers would block the frontend's access to the JSON server.
Run `docker-compose -f docker-compose-dev.yml up` and open a page that needs to access API in a modern browser. The browser should block CORS access without this PR.
The frontend should correctly access the JSON API.
> Disable CORS on mock server

- layouts/default.vue
- pages/conference/schedule.vue
* Add `keep-alive` on `<Nuxt />` to preserve the state.
* Setting `scrollPosition` that we want to keep in `PageConferenceSchedule`.
1. Go to schedule page
2. Click on any speech
3. Go to previous page(schedule page)
4. The position of slider is maintained
The tab & slider position should be the same as last visited.
#183
> feat(pageconferenceschedule): use keep-alive and set scrollPosition

- components/schedule/ScheduleEvent.vue
- plugins/strings.js
Add timezone format option plugin to string.js and display on schedule event
resolve #185 
Please visit page  **/2022/zh-hant/conference/schedule**, 
and see if time duration display like this →  **16:30 ~ 16:45 (GMT+8)**
#185 [Display timezone information on schedule page](https://github.com/pycontw/pycontw-frontend/issues/185)
> feat(schedule): add timezone display on schedule time duration

- components/core/header/nav-bar/nav-bar-items.js
- components/events/EventCard.vue
- components/events/EventCardCollection.vue
- i18n/events/overview.i18n.js
- pages/events/overview.vue
Following spec that revamping the style of event overview page.
1. Go to page `events/overview`
closes #199
> style(events/overview): revamp page event-overview

- pages/events/sprints.vue
Add the embedded hackmd of sprint details
> feat(sprint): add embedded hackmd iframe

- i18n/conference/keynotes.i18n.js
- i18n/conference/speeches.i18n.js
Update `Talks` and `Tutorials` page contents to disclose how to join speeches and Q & A sections this year.
Also update keynote speakers count from 4 to 5.
Reference doc: https://docs.google.com/document/d/1Ef7Ob3Jtuk0ugoDdOJ0KdLkkBLOV8QtgGxzVqSTfllY/edit?usp=sharing
1. Setup environment and run server
2. Go to `/conference/talks` and `/conference/tutorials` to check content has been updated. Also check `/conference/keynotes` for updated keynote info. 
- The contents in talks and tutorials should be updated.
- The count of keynote speakers change from 4 to 5.
No
No
> feat(talks, tutorials): Update the content of talks and tutorials, and fix keynotes info

- components/core/header/HomeIcon.vue
- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarItemDropdown.vue
- components/core/header/nav-bar/ScrollableNavBar.vue
* **Bugfix**
Navbar items will auto wrap when browser's width is too small, and we don't wnt it.
1. Open any page.
2. Testing RWD for the no-wrape style of navbar item.
> Navbar nowrap

- Dockerfile
- components/core/footer/Footer.vue
- components/core/footer/FooterHistory.vue
- components/core/header/HomeIcon.vue
- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarHamburger.vue
- components/intro/Intro.vue
- docker-compose-dev.yml
- docker-compose.yml
- layouts/default.vue
- nuxt.config.js
- pages/about/privacy-policy.vue
- pages/events/overview.vue
- pages/index.vue
- store/index.js
Change all "PyCon APAC" into "PyCon TW", 2022 -> 2023 for the CfP stage.
1. npm run dev
1. Showing `speaking/`, `overview/` pages with conference name as PyCon TW.
2. Hiding `about/staff/`, `schedule/`, `conference/`, `events/`, `registration/` pages
Closes #342
> feat: change PyCon APAC -> PyCon TW, 2022 -> 2023

- components/core/buttons/TextButton.vue
- tailwind.config.js
- Update the color of `pink-700` to `#da8bdc`
- Update the gradient color of `TextButton`
- Update the gradient color of hover `TextButton`
- Figma: https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=5132%3A38362&t=sAc3t8ndcOZ5K7jB-0    
https://user-images.githubusercontent.com/11289171/204591812-515bf67d-0cd5-4333-80cb-9cfa8aa1f77b.mov
https://github.com/pycontw/pycontw-frontend/issues/344
NA
> [#344] style: update gradient colors of button and text color when hover navbar

- i18n/speaking/cfp.i18n.js
* **Bugfix**
- CFP 頁面：公民科技前加上頓號
- Path: `/speaking/cfp`
- Check both zh-hant and English.
#336 
NA
> [336] fix: missing comma

- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarHamburger.vue
- store/index.js
feat: add switch to decide whether showing overview page or not
1. Go to home page and check if `events/overview` is displayed on the navigator or hamburger  navigator
fix #370
> feat: add switch to decide whether showing overview page or not

- components/core/header/Header.vue
- components/core/header/nav-bar/NavBar.i18n.js
- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarHamburger.vue
- i18n/speaking/cfp.i18n.js
- pages/speaking/cfp.vue
* rename "sign in" to "proposal system"
1. go to homepage
> feat(navigator): rename sigh in to proposal system

- pages/index.vue
* **Bugfix**
- 調整 Landing Page `min-height`
https://user-images.githubusercontent.com/11289171/219846651-fd5cfd46-7f34-45bb-ad73-f88ab030635a.mov
#374 
NA
> [374] style: adjust min-height of landing page

- configs/router.js
- nuxt.config.js
- package-lock.json
- package.json
* **Bugfix**
fix 404 error page on google cache page
open in google link site:https://tw.pycon.org
choose in search result "頁庫存擋"
you open page https://webcache.googleusercontent.com/search?q=cache:9er0RXJ1v60J:https://tw.pycon.org/&cd=1&hl=zh-TW&ct=clnk&gl=tw&cd=1&hl=ru&ct=clnk&gl=ua
then page will redirect to https://tw.pycon.org/2023/en-us/search?q=cache%3A9er0RXJ1v60J%3Ahttps%3A%2F%2Ftw.pycon.org%2F&cd=1&hl=zh-TW&ct=clnk&gl=tw
show correctly on webcache page
refer to https://github.com/vuejs/vue-router/issues/2042
> fix: webcache 404 error page

- i18n/events/sprints.i18n.js
- pages/events/sprints.vue
- store/index.js
Update page related to sprints and upload to 2023 website
1. click events/sprints in header
2. check if En/Zh content updated to 2023 information at Google [Doc](https://docs.google.com/document/d/1jZ9v_Fsc0dgWFB7TmQ8b4mclJBkqPoc9bwjQ9sdU12I/edit#heading=h.z437yptlh9hp) 
#427
> feat- add 2023 sprints page

- components/schedule/ScheduleEvent.vue
- pages/conference/keynotes.vue
* **Bugfix**
* prevent replaceAll on null when speaker_name_en_us is empty
1. go to page http://localhost:3000/2023/zh-hant/conference/keynotes or http://localhost:3000/2023/en-us/conference/keynotes
> fix(keynote): prevent replaceAll on null when speaker_name_en_us is empty

- components/sponsors/SponsorCard.vue
* **Bugfix**
adjust tag position and remove border radius of sponsor logo
1. go to index page
Before
After
> fix(index/sponsorCard): adjust sponsorCard__tag position and remove logo border radius

- i18n/about/history.i18n.js
- pages/about/history.vue
> feat(about/history): add 2023 history

- pages/registration/tickets.vue
* **Bugfix**
ui is not align on ticket info page
check out ticket info page
> fix(ticket): ui broken on ticket info

- components/core/header/Header.vue
- components/core/header/HomeIcon.vue
- components/core/header/locale-switch/LocaleSwitch.vue
- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarItemDropdown.vue
- components/core/header/nav-bar/ScrollableNavBar.vue
#429
* **Bugfix**
* reduce horizontal padding in header
1. Go to index page
#429
> fix(header): reduce horizontal padding in header

- i18n/index.i18n.js
- package-lock.json
- package.json
- pages/index.vue
Show typhoon information once entering landing page
#453
> feat-typhoon pop up info

- package.json
* **Bugfix**
Since we  notice the [error here](https://github.com/pycontw/pycontw-frontend/actions/runs/7256735907), `npm generate` is missing in the `package.json` file.
> Add Generate Command Back

- components/core/header/nav-bar/NavBar.vue
- components/core/header/nav-bar/NavBarHamburger.vue
- i18n/speaking/cfp.i18n.js
- store/index.js
Hide proposal system temporarily before bugs fixed.
Add parameter that makes hiding proposal system easier.
More specifically, hide or remove links for items with red frame as following:
> hide proposal system temporarily

- configs/pageLanding.js
* **Bugfix**
fix #467 issue
1. Navigate to 'https://tw.pycon.org/2024/zh-hant'.
2. Observe the "Join Us" and "Call for Proposals" buttons in the middle section of the homepage.
1. The button size should be consistent.
> fix(homepage): adjust the join_us button setting

- pages/index.vue
- store/index.js
Please note that the CD (netlify) has broken due to other issue, but the change work on my local (preview as follow):
> chore: hide cfp button on index page

- i18n/speaking/cfp.i18n.js
- pages/speaking/cfp.vue
Current page [call for proposal](https://tw.pycon.org/2024/en-us/speaking/cfp) is 2023. Update content to 2024 version and
hide button temporarily as the following picture till other pages prepared:
文案：[2024 Link](https://github.com/pycontw/pycontw-program-2024/commit/a6e4e4649053f5d6864325ebb5e746e7cdd260b8#diff-af900dcbb43b504f2821966c82110c937612f487c6eb9af8f9af23a1e927789d)
#463 
#468
> Update 2024 cfp

- i18n/sponsor/index.i18n.js
Current text on [sponsor page](https://tw.pycon.org/2024/zh-hant/sponsor) is not in desired format.
Corrent format should be like that:
#468
> fix-adjust content format of sponsor

- nuxt.config.js
- store/index.js
Enhancement according to  #507
update to prevent all failures when getting talks/tutorials
- Neltify build should be successful
#507
> fixup! fix: prevent generation failed due to 4xx, 5xx api error

- i18n/about/privacy-policy.i18n.js
- pages/about/privacy-policy.vue
1. remove unused `label: 'https://i.imgur.com/cVjN760.jpg'` in `i18n/about/privacy-policy.i18n.js`
2. remove i18n-unrelated code `terms.contact` and move it in template (`terms.contact` doesn't require translation)
3. replace (CC BY-SA 3.0 TW) with `{licenseTitle}` for better maintenance
#499 
I was also going to rewrite the styling in `pages/about/privacy-policy.vue` with respect to #396,
but found that tailwind inline classes will be overridden by ones in `I18nPageWrapper`.
Maybe we could add `important: true` in `tailwind.config.js` to make switching to tailwind css easier?
> [feat] remove i18n-unrelated code in provacy-policy page

- layouts/default.vue
Update og-img to current year
Fix the bug on outdated og img when the official website link shared
* **Bugfix**
1. Share the link of "https://tw.pycon.org/"
2. Check if the img is 2024 (especially the date of conference on the img) with the link
> fix: outdated og-img

- pages/conference/keynotes.vue
- store/index.js
Fix #526 
1. Toggle On keynote page.
2. Fix the javascript replaceAll error, because of old node js version.
1. Go to path `2024/zh-hant/conference/keynotes`
keynote Screenshot:
> feat(keynote): toggle keynote and fix js error in server

- pages/conference/keynotes.vue
* **Bugfix**
- center the keynote profile img.
Go to keynote page and observe the img is center?
https://deploy-preview-542--classy-granita-bc2b5a.netlify.app/en-us/conference/keynotes
> fix(keynote): center the img in keynote

- routes.json
* **Bugfix**
issue: https://github.com/pycontw/pycontw-frontend/pull/550#issuecomment-2202667612
the behavior of how json-server reads the route settings seems to be changed. 
When requesting `/api/events/speeches/category/:category`, the json-server incorrectly matches the route `/api/events/speeches/:event_type/:id` (take `category` as even type, and `:category` as the id). Changing the sequence in routes.json solves this issue.
> fix(dev): json-server does not return correct speech data

- i18n/conference/speeches.i18n.js
- store/index.js
Switch on 2024 Tutorials(專業課程) and Talks(一般演講) pages
1. Go to path/2024/zh-hant/conference/talks 
2. Go to path/2024/zh-hant/conference/tutorials 
3. Check if they can be entered from navigation bar "Conference/Talks" and "Conference/Tutorials"
#529 
#528
> feat(speech): toggle talks and tutorials pages

- components/core/modal/Modal.vue
* **Bugfix**
Logo affected by rounded feat for inner photo in sponsor card. 
Remove it to show the complete content.
1. Go to path/2024/zh-hant and click on sponsor logos to check if photos are fixed.
e.g:
> fix(modal): remove inner photo rounded for sponsor logos

- components/core/header/nav-bar/NavBar.i18n.js
- components/core/header/nav-bar/nav-bar-items.js
- i18n/about/history.i18n.js
- i18n/about/index.i18n.js
- i18n/conference/poster-session.i18n.js
- pages/conference/poster-session.vue
Poster Session is a single event with multiple posters at this year's conference, unlike talks and tutorials, which are multiple events each with a specific topic. 
I made some adjustments to ensure the naming in the code fits this context.
> refactor(conference): naming in poster-session 

- pages/conference/poster-session.vue
* **Bugfix**
Fix the broken UI in the pop-up poster info.
1. Go to path/2024/zh-hant/conference/poster-session
2. Switch to RWD mode with Inspect tools.
3. Click Responsive dorpdown menu choose the small one (iPhoneSE).
4. Click on the poster titled “從台灣走向國際、從源來適你走向開源” and check if the err is still there.
text of description of poster-session stay in border when use of RWD model.
> fix(poster-session): fix font size on RWD

- store/index.js
put back "showConferencePage" deleted by mistake.
> fix(nav-bar): put back "showConferencePage"

- i18n/sponsor/index.i18n.js
- pages/sponsor/index.vue
Remove content that does not require i18n conversion.
1.  Into pages/sponsor/index.vue
2.  Check line 54 in index.vue if $t('terms.contact') become sponsorship@python.tw or not
3. Into i18n/sposor/index.i18n.js
4. Check if terms: {contact: 'sponsorship@python.tw', } has been removed from both en-us and zh-hant in index.i18n.js.
5. Into http://localhost:3000/2024/en-us/sponsor 
6. Check if sponsorship@python.tw showed normally or not
> refactor(sponsor): non-i18n content adjustment

- i18n/ext/discord.i18n.js
- pages/ext/discord.vue
Update Discord usage page
1. run `npm run dev`
2. go to `http://localhost:3000/2024/zh-hant/ext/discord`
<details>
<summary>中文</summary>
</details>
<details>
<summary>EN</summary>
</details>
> feat(ext/discord): update content

- nuxt.config.js
* **Bugfix**
Updated `nuxt.config.js` to use `publicRuntimeConfig.http.browserBaseURL` for dynamic API base URL injection.
- Navigate to https://staging.pycon.tw/2025/zh-hant/conference/keynotes
- On first load (SSR), the API calls (for keynotes, talks, etc) go to: https://staging.pycon.tw/prs/...
- But after you navigate to another route and then back to /conference/keynotes:
- The client-side code can no longer see process.env.BASE_URL.
- The code falls back to the default (possibly https://tw.pycon.org/prs), not the staging API URL
- Set a custom BASE_URL in your environment variables.
- Start the Nuxt app and load a page (SSR).
- Navigate between pages (client-side) and verify that API requests continue to use the correct base URL.
Reference: https://http.nuxtjs.org/api/runtime-config
> fix(nuxt.config.js): add runtime config for api base url

- pages/events/overview.vue
- Update sprint event classification in events overview page
- Change eventTag from 'post_event' to 'warmup' to reflect sprint development as a pre-conference activity
>   update(events): change sprint event tag from post-event to warmup

- components/core/embed/Youtube.vue
- components/core/tabs/Tab.vue
- pages/conference/_eventType/_id.vue
- pages/conference/keynotes.vue
* **Bugfix**
iframe 加上 `loading='lazy'`，並把 tab 的 `isActive` 預設值改成 `false`，否則 iframe 還是會在進入頁面就載入 (chrome)。
#641
> feat: lazy-loading iframes in keynotes and talks pages

- pages/index.vue
* **Bugfix**
- Removed an unused `// eslint-disable-line` comment from the `showSwal`
- Run `npm run dev`without any exception happens.
> fix: remove unnecessary eslint-disable comment in Swal method

- components/core/header/nav-bar/nav-bar-items.js
> 移動  Lightning Talk 閃電秀  菜單上 排序

- components/schedule/ScheduleGrid.vue
- components/schedule/ScheduleRoom.vue
* **Bugfix**
- Add room labels for 2-all (empty) and 3-r0-all (All Rooms) in ScheduleRoom component
- Add CSS grid-column rules for room-3-r0-all to span R0-R4 rooms consistently with room-2-all
- Ensure cross-room events display properly across both day1 and day2 schedules
- Fix missing room label display for registration and welcome events
> fix: add CSS grid support for room-3-r0-all schedule events

- components/schedule/ScheduleRoom.vue
* **Bugfix**
Hide empty `ScheduleRoom` component when `name` is empty.
1. Go `/zh-hant/conference/schedule` (with mobile viewport)
2. Scroll to registration & Breakfast
The top-left empty circle is hidden.
Fixed #713
> fix: hide empty `ScheduleRoom` component

- components/schedule/ScheduleBlock.vue
* **Bugfix**
Set `locale-link` from `ScheduleBlock` to fill the parent size.
1. Go `/2025/zh-hant/conference/schedule` (on desktop)
2. Click on the empty area of the schedule event block
Able to navigate
https://github.com/user-attachments/assets/77f5301b-c631-4a97-987e-5f4270541101
Fixed #711
> fix: expand `ScheduleBlock` link click area
